version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    links:
      - "redis:redis"
  redis:
    image: 'redis'
    command: redis-server --requirepass 1nUMbNBIqI8b
    ports:
      - '6379:6379'
